title: ESP32 SmartPlug made for ESPHome
description: Smart Plug with ESP32 WROOM and an embedded STHC3 temperature and humidity sensor. Vaiotech Limited (New Zealand, 2022).
theme: jekyll-theme-slate
